### ISSUE TITLE
[Bug] ImHex crash

### ISSUE THREAD

**Issue by TheEZIC** [WerWolv/ImHex#1179] opened 2023-07-02 13:37 UTC
### Operating System

Windows

### What's the issue you encountered?

ImHex crashed with following error:
[16:23:18] [INFO]  [main] Welcome to ImHex 1.30.1!
[16:23:18] [INFO]  [main] Compiled using commit master@cc55ca3
[16:23:18] [INFO]  [main] Native scaling set to: 1.0
[16:23:18] [INFO]  [main] Task 'Setting up environment' finished in 0 ms
[16:23:18] [INFO]  [main] Task 'Creating directories' finished in 2 ms
[16:23:18] [INFO]  [main] Task 'Loading settings' finished in 0 ms
[16:23:18] [INFO]  [builtin] Found crash.json file at C:\Users\TheEZIC\AppData\Local\imhex\config\crash.json
[16:23:18] [INFO]  [main] Task 'Loading plugins' finished in 22 ms
[16:23:19] [INFO]  [main] Task 'Checking for updates' finished in 675 ms
[16:23:19] [INFO]  [main] Task 'Loading fonts' finished in 756 ms
[16:23:19] [INFO]  [main] Running on Windows 10.0.19044 (x86_64)
[16:23:19] [INFO]  [main] Using 'NVIDIA Corporation' GPU
[16:25:15] [FATAL] [main] Exception raised: 0xC0000005
[16:25:15] [FATAL] [main] Terminating with signal 'SIGSEGV' (11)
[16:25:15] [FATAL] [main] Received signal 'SIGSEGV' (11)
[16:25:15] [INFO]  [main] Wrote crash.json file to C:\Users\TheEZIC\AppData\Local\imhex\config\crash.json
[16:25:16] [FATAL] [main]   atexit
[16:25:16] [FATAL] [main]   atexit
[16:25:16] [FATAL] [main]   atexit
[16:25:16] [FATAL] [main]   atexit
[16:25:16] [FATAL] [main]   (C:\M\B\src\mingw-w64\mingw-w64-crt\crt\crt_handler.c:214) | _gnu_exception_handler
[16:25:16] [FATAL] [main]   _C_specific_handler
[16:25:16] [FATAL] [main]   _chkstk
[16:25:16] [FATAL] [main]   RtlRaiseException
[16:25:16] [FATAL] [main]   KiUserExceptionDispatcher

### How can the issue be reproduced?

I just wrote code in pattern editor and then press run button.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by iTrooz** [comment] 2023-07-02 13:39
Hey, can you provide an example file and pattern with which you can reproduce the bug ?

**Comment by TheEZIC** [comment] 2023-07-02 13:50
[btl000.dds.zip](https://github.com/WerWolv/ImHex/files/11929674/btl000.dds.zip)

```
struct Header {
    char signature[4];
    u32 size;
    u32 magick1;
    char platform[4];
};

struct Entry {
    u32 magick1;
    u32 magick2;
    u32 magick3;
    u32 magick4;
};

Header header @ 0x00;
Entry entries[41] @ 0x238;
```

**Comment by iTrooz** [comment] 2023-07-02 13:54
I can't reproduce the crash with the v1.30.1 release on Arch Linux unfortunately

Anyone else could try to reproduce it on Windows ?

In the meantime @TheEZIC , could you also post a video showing everything, from ImHex launch to the crash ?
Could you also try with the latest nightly build ?

**Comment by TheEZIC** [comment] 2023-07-02 14:06
This video recorded on this version:
https://github.com/WerWolv/ImHex/releases/tag/v1.30.1

https://github.com/WerWolv/ImHex/assets/35061249/5b9fd3d0-5936-403b-a4c4-a298f4287661

**Comment by iTrooz** [comment] 2023-07-02 14:08
Ohhh so the bug happens when you click multiple times quickly.

In that case, this is probably a bug we already know about. We tried to fix it since the release, could you try the latest nightly ?

**Comment by TheEZIC** [comment] 2023-07-02 14:09
No, it's sometimes works on second click after a long time from first. I've clicked fast on this video just for bug reproduction

**Comment by iTrooz** [comment] 2023-07-02 14:10
Okay. Could you still try the nighly ?

**Comment by TheEZIC** [comment] 2023-07-02 14:11
Nighly seems to works well. Without crashes

**Comment by iTrooz** [comment] 2023-07-02 14:13
Nice ! Not sure what was causing it then, but since it's fixed in the nightly, I'm going to mark this as closed. Thanks !

**Closed by iTrooz** 2023-07-02 14:13 UTC
Labels: bug
