### ISSUE TITLE
[Bug] Data Inspector View crashes app

### ISSUE THREAD

**Issue by masagrator** [WerWolv/ImHex#304] opened 2021-09-20 19:26 UTC
### Operating System

Windows 11

### What's the issue you encountered?

Data Inspector view crashes Imhex in portable version if I will set view to hexadecimal. Without any error, just closes.

### How can the issue be reproduced?

1. Open any file in ImHex
2. Open Data Inspector View
3. Select Hexadecimal

### ImHex Version

1.9.0

### Additional context?

- Portable version
Attached file I have used for testing. It's a RGBA8 raw image with custom header.
[options_tab.zip](https://github.com/WerWolv/ImHex/files/7198220/options_tab.zip)

**Comment by WerWolv** [comment] 2021-09-20 20:09
Hi! Could you try with the [latest nightly](https://github.com/WerWolv/ImHex/suites/3820294437/artifacts/94531352) of ImHex? I fixed a bug after releasing 1.9.0 that causes crashes if the selected value wasn't a valid UTF16 character so I'm wondering if that's the problem since I can't reproduce it with my dev build

**Comment by masagrator** [comment] 2021-09-20 20:43
> Hi! Could you try with the [latest nightly](https://github.com/WerWolv/ImHex/suites/3820294437/artifacts/94531352) of ImHex? I fixed a bug after releasing 1.9.0 that causes crashes if the selected value wasn't a valid UTF16 character so I'm wondering if that's the problem since I can't reproduce it with my dev build

With this build is not crashing.

**Comment by WerWolv** [comment] 2021-09-20 21:15
Awesome. Closing as fixed

**Closed by WerWolv** 2021-09-20 21:15 UTC
