### ISSUE TITLE
[Bug] -Werror=maybe-uninitialized

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [WerWolv/ImHex#1011] opened 2023-04-04 21:27 UTC
### Operating System

Linux

### What's the issue you encountered?

Unable to compile from source due to possible uninitialised variables.

### How can the issue be reproduced?

compile with commit https://github.com/WerWolv/ImHex/commit/3658d8d96e7180842f45f87437c10ab7e5099cbc.

### ImHex Version

3658d8d96e7180842f45f87437c10ab7e5099cbc

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Git

### Additional context?

Output of `make -B 2> /tmp/errors.txt`: [errors.txt](https://github.com/WerWolv/ImHex/files/11153374/errors.txt)
**Specs (almost forgot):** https://linux-hardware.org/?probe=b5740f3323

**Comment by WerWolv** [comment] 2023-04-04 21:43
Thank you. Try again with the latest commit. Also make sure the pattern_language submodule gets updated to the latest commit

**Comment by gareth-anthony-hulse** [comment] 2023-04-04 22:00
Still not working: [errors.txt](https://github.com/WerWolv/ImHex/files/11153580/errors.txt)
````
$ git submodule update --force 
Submodule path 'lib/external/capstone': checked out 'd5141c04785678535c7792eddc21f146186e639f'
Submodule path 'lib/external/curl': checked out 'b16d1fa8ee567b52c09a0f89940b07d8491b881d'
Submodule path 'lib/external/fmt': checked out 'a33701196adfad74917046096bf5a2aa0ab0bb50'
Submodule path 'lib/external/libromfs': checked out '40cd303e9213e544a3ff21562b16406140f254ec'
Submodule path 'lib/external/libwolv': checked out '34d36a2f3397143a79b31fa4ba0f57f91ba0600e'
Submodule path 'lib/external/nativefiledialog': checked out '7909f55d912fe353ee2df6b08eec9313b50685f7'
Submodule path 'lib/external/pattern_language': checked out '8431d3a5c3734682cec6740f8b5368a08eddb08b'
Submodule path 'lib/external/xdgpp': checked out 'f01f810714443d0f10c333d4d1d9c0383be41375'
Submodule path 'lib/external/yara/yara': checked out '96790e56fc0fc0ce8598d215f969d8b7d8ca1015'
````

**Comment by WerWolv** [comment] 2023-04-04 22:18
What compiler / compiler version are you using? I can build it just fine on both Windows and Arch Linux using GCC 12.2.1

**Comment by gareth-anthony-hulse** [comment] 2023-04-04 22:23
As a work around, I edited `/usr/include/c++/12.2.1/bits/random.h`: changed line 1577 to `double __x = 0;` and line 1600 `double __v = 0` which allows me to compile.

**Comment by gareth-anthony-hulse** [comment] 2023-04-04 22:24
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.1 20230201 (GCC) 
```

**Comment by WerWolv** [comment] 2023-04-05 05:24
Fastscinating, I think that's actually a bug in gcc's code. Looking through that function, `__x` and `__v` are actually not always initialized. Might be worth reporting this to their issue tracker.

I'll disable the warning for this region of code for now until it's fixed on their side

**Comment by gareth-anthony-hulse** [comment] 2023-04-05 10:21
When reversing the changes I made with `/usr/include/c++/12.2.1/bits/random.tcc`, I still get the same errors with 89aee456c6cd897ea7e998340ded2004d3638412. Log: [errors.txt](https://github.com/WerWolv/ImHex/files/11157664/errors.txt)
```
$ git show --oneline -s
89aee45 (grafted, HEAD -> master, origin/master, origin/HEAD) patterns: Updated pattern language
```
```
$ git submodule update --force
Submodule path 'lib/external/capstone': checked out 'd5141c04785678535c7792eddc21f146186e639f'
Submodule path 'lib/external/curl': checked out 'b16d1fa8ee567b52c09a0f89940b07d8491b881d'
Submodule path 'lib/external/fmt': checked out 'a33701196adfad74917046096bf5a2aa0ab0bb50'
Submodule path 'lib/external/libromfs': checked out '40cd303e9213e544a3ff21562b16406140f254ec'
Submodule path 'lib/external/libwolv': checked out '34d36a2f3397143a79b31fa4ba0f57f91ba0600e'
Submodule path 'lib/external/nativefiledialog': checked out '7909f55d912fe353ee2df6b08eec9313b50685f7'
Submodule path 'lib/external/pattern_language': checked out '75c6ce400a507f96b49a35168c41071ea4a86f63'
Submodule path 'lib/external/xdgpp': checked out 'f01f810714443d0f10c333d4d1d9c0383be41375'
Submodule path 'lib/external/yara/yara': checked out '96790e56fc0fc0ce8598d215f969d8b7d8ca1015'
```

**Comment by WerWolv** [comment] 2023-04-05 16:04
Please try again now. I disabled the warning on the entire file now

**Comment by gareth-anthony-hulse** [comment] 2023-04-05 17:20
Still not working. I've tried adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-maybe-uninitialized")` to ImHex's `CMakeLists.txt` and that allows me to compile.

**Comment by WerWolv** [comment] 2023-04-05 17:22
Seriously what the fuck

That's unfortunately no solution for me because that warning is very useful under normal circumstances, it's really just problematic right now because the bug is apparently in the standard library. I'm honestly not quite sure how to continue now

**Comment by gareth-anthony-hulse** [comment] 2023-04-05 17:37
GCC bug, again?  Another option would be `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=maybe-uninitialized")`, so that is `-Wmaybe-uninitialized` is only a warning and allows for compilation.

**Comment by gareth-anthony-hulse** [comment] 2023-04-05 17:48
It is odd that GCC diagnostic won't ignore `-Wmaybe-uninitialized`.

**Comment by WerWolv** [comment] 2023-04-05 18:05
I assume this is an issue due to the hardening flags your distro forcefully enabled on your compiler so even disabling the warning just still keeps it on. Because of that and because I literally can't reproduce it on any of my machines, honestly I'd say this is a "not my problem" issue. It's a bug in libstdc++ that, together with your distro's compiler flags, causes the build error. 
If you want this fixed in a better way, I suggest you to take this bug to the GCC issue tracker and maybe to your distro's support group, they will be able to do more than I can. I'll leave the comment and the attempted diagnostics ignore pragma in my code for now so it can maybe be used as an example. 

For now, I guess just manually pass `CMAKE_CXX_FLAGS="-Wno-maybe-uninitialized"` to your cmake command until the issue is fixed upstream. 
I'm sorry I can't do much more for you here.

**Closed by WerWolv** 2023-04-05 18:05 UTC
Labels: bug
