### ISSUE TITLE
[Bug] error[E0011]: Memory error. Tried accessing out of bounds heap cell 2. This is a bug.

### ISSUE THREAD

**Issue by sagasm** [WerWolv/ImHex#1112] opened 2023-05-27 21:48 UTC
### Operating System

Windows

### What's the issue you encountered?

trying to write a parser to return a structure.

### How can the issue be reproduced?

Use the provided files as input and pattern. Try to run the pattern and when it finishes scroll down the console output window to see the error. 
[test.zip](https://github.com/WerWolv/ImHex/files/11583068/test.zip)

### ImHex Version

1.29

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment] 2023-05-27 22:54
your zip file only contains a pattern and has no input file to test it. Note my almost identical bug #1038 was fixed and is closed but that was on sections and this is not. Please submit the file in which to run this pattern to produce the error.

**Comment by sagasm** [comment] 2023-05-27 23:01
Data file:
[Uploading Codesys.zip…]()

**Comment by iTrooz** [comment] 2023-05-27 23:05
(You didn't upload your file)

**Comment by paxcut** [comment] 2023-05-27 23:05
that link doesnt work

**Comment by sagasm** [comment] 2023-05-27 23:13
Sorry...
[Codesys.zip](https://github.com/WerWolv/ImHex/files/11583193/Codesys.zip)

**Comment by paxcut** [comment] 2023-05-28 01:10
I think the problem is trying to return the structure from a function and assigning it by value. A work around would be passing the structure as a reference and assigning to it directly.

**Comment by sagasm** [comment] 2023-05-28 01:25
I also tried to pass the structure as a reference but don't work: #1113

**Comment by paxcut** [comment] 2023-05-28 16:25
The problem here is that the main scope doesn't know how to deal with custom types that are not defined in it. In this case defining a dummy variable is enough to let the global scope what to do.
```cpp
#include <std/io.pat>

struct MBUIDecoder
{
   u32 data;
   u32 len;
};

MBUIDecoder dummy;

fn test(auto pos)
{
    MBUIDecoder ret;
    
    std::print("Before Assign -> len={},data={:08x}",ret.len,ret.data);
    ret.data=2;
    ret.len=3;
    std::print("Before return -> len={},data={:08x}",ret.len,ret.data);
    return ret;
};

struct MBUI
{
    u32 a=0;
    u32 start=$;
    std::print("start={:08x}",start);

    MBUIDecoder ret=test(0);
    std::print("After return -> len={:08x},data={:08x}",ret.len,ret.data);

};

struct mbuiTest
{
    MBUI a;
};

mbuiTest tt@1;
```
This pattern used in the input file you provided results in the output
```
start=00000001
Before Assign -> len=0,data=00000000
Before return -> len=3,data=00000002
After return -> len=00000003,data=00000002
Pattern exited with code: 0
Evaluation took 0.0010238s
```

**Comment by sagasm** [comment] 2023-05-29 01:25
tks

**Comment by iTrooz** [comment] 2023-06-03 17:08
Hey, can this issue be closed ?

**Comment by paxcut** [comment] 2023-06-04 06:19
I have notified original author about closing issues that are resolved which in this case it seems to me that it is based on his last response.

**Closed** 2023-06-04 08:05 UTC
Labels: bug
