### ISSUE TITLE
[Bug] Windows: Crash when opening any file

### ISSUE THREAD

**Issue by mi-hol** [WerWolv/ImHex#886] opened 2023-01-16 10:26 UTC
### Operating System

Windows

### What's the issue you encountered?

Just like described in #881 
I'm using Windows 11 Pro

![image](https://user-images.githubusercontent.com/22799428/212655721-c4d6571e-e34f-4bb2-89bf-35e73f2c1833.png)

### How can the issue be reproduced?

yes, I tried even with a plain txt file, ImHex window just closed after the file was selected and confirmed with ok

Is there a "debug" option that will produce a trace?

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable NoGpu zip extracted to C:\Program Files\ImHex

**Comment by WerWolv** [comment] 2023-01-16 11:12
I still can't reproduce it, even with your steps. 
There aren't any debug builds readily available but you can build one yourself using msys2 on Windows. Just pass `-DCMAKE_BUILD_TYPE=Debug` to cmake before building

**Comment by mi-hol** [comment] 2023-01-16 11:49
> but you can build one yourself using msys2 on Windows. Just pass `-DCMAKE_BUILD_TYPE=Debug` to cmake before building

there is the invalid assumption that a matching build environment setup is present!

Even with a "Debug build" would a usable trace file be produced?
https://github.com/WerWolv/ImHex/blob/master/HACKING.md contains no hints about this topic.

So I and others reporting the same issue are stuck!

**Comment by WerWolv** [comment] 2023-01-16 12:20
The HACKING.md file explains the things that are needed to setup a dev environment if you don't have one yet. It explains everything that's specific to building ImHex.
A debug build would just allow you to attach a debugger to properly see where the crash happens. This kind of knowledge just goes way beyond what a help file like this should include because you find much better explanations online.

I'll close this issue here as it's a duplicate of #881 so we can aggregate all information in one place

**Comment by mi-hol** [comment] 2023-01-16 12:21
Tried with older  Windows versions but none of them even opens after clicking on exe in Explorer.
Chanching Windows compatibility setting brough no cure.

I'd assume a dependency for running exe is not met

```
winget install WerWolv.ImHex --version 1.25.0
winget install WerWolv.ImHex --version 1.24.3
```

**Comment by mi-hol** [comment] 2023-01-16 12:21
> duplicate of #881 so we can aggregate all information in one place

was already closed too

**Closed by WerWolv** 2023-01-16 12:20 UTC
Labels: bug

**Comment by WerWolv** [comment] 2023-01-16 12:23
> Tried with older Windows versions but none of them even opens after clicking on exe in Explorer.

`winget` installs the GPU accelerated version of ImHex so if your system doesn't have a GPU, it won't run.

> was already closed too, so how would that help?

I reopened it now because obviously the issue still happens to some people

**Comment by mi-hol** [comment] 2023-01-16 12:53
> A debug build would just allow you to attach a debugger to properly see where the crash happens.

I'm not C++ developer, so the proposed option is not helpful :(
