### ISSUE TITLE
[Bug] Random freezes on Windows

### ISSUE THREAD

**Issue by childen** [WerWolv/ImHex#747] opened 2022-09-19 11:45 UTC
### Operating System

Windows

### What's the issue you encountered?

Random freezes. The UI freezes randomly. ImHex can then only be killed using the task manager.

### How can the issue be reproduced?

Start ImHex. Open any hex file. Do some work.

Crashes occured during 
* window resizing
* Directly after opening a recent file
* During Navigation in Pattern Data table
* During selection of bytes in hex editor view

### ImHex Version

1.23.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Please let me know if I can provide a crash dump or anything else that might be helpful to isolate the issue.

**Comment by siddhipatel184** [comment] 2023-01-02 21:48
Have you tried considering changing your hard drive and/or expanding your disk capacity ?

**Comment by Nemoumbra** [comment] 2023-11-12 12:38
I'm unable to reproduce any crashes from the aforementioned list. I remember we fixed one crash related to resizing half a year ago.
Please check out the current Nightly build and report if the issues are still present.

**Closed** 2023-11-12 21:19 UTC
Labels: bug
