### ISSUE TITLE
[Bug] Icon disappeared on macOS

### ISSUE THREAD

**Issue by zer0pwned** [WerWolv/ImHex#414] opened 2022-02-05 23:43 UTC
### Operating System

MacOS

### What's the issue you encountered?

The cool icon of ImHex application is gone on macOS and only shows default blank icon template. Plus, the OS always complains the app quit unexpectedly even just open it and click the close button of it right away. It does not matter b/c the application is still functional when I open it next time, just bit of annoying. 

<img width="247" alt="image" src="https://user-images.githubusercontent.com/3125626/152662586-84db6d34-6643-41ef-abcd-a61b0a0248f8.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/3125626/152662620-4d5c3ef4-a221-4265-871b-580c84a866ed.png">

### How can the issue be reproduced?

For the first issue I think it is more or less building/packing issue. As for the second issue, I'm not sure if it is just me but I can stably reproduce it every time when I try to close the application. 

### ImHex Version

1.14.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- macOS Monterey 12.2/Apple M1 Pro.

**Comment by WerWolv** [comment] 2022-02-05 23:50
Hey

I know about the issues with the icon on mac, the problem is I have absolutely no idea what causes it. And since I have no mac myself, there's no way for me to debug it. If you have an idea or can try compiling ImHex yourself and trying around a bit I'd be really grateful. The issue is somewhere in the CMake build script.

The crashes _should_ be fixed in the nightly release.

**Closed** 2022-02-06 21:29 UTC
