### ISSUE TITLE
[Feature] Fedora/EPEL packaging

### ISSUE THREAD

**Issue by jonathanspw** [WerWolv/ImHex#595] opened 2022-07-28 17:53 UTC
### What feature would you like to see?

Hi,

I'm a packager for Fedora/EPEL and am willing to package this for native OS repositories but I need a little help from you.

Per Fedora's packaging guidelines packages need to be built against libs available within the OS so I need a way to instruct make to compile using OS libraries for everything and not the packages dependencies.

Can you provide a flag to accomplish this?

#314 shows there is at least some interest in packages being available in the Fedora repositories.

### How will this feature be useful to you and others?

More people will be able to more easily get/use ImHex :)

### Request Type

- [X] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment] 2022-07-28 20:31
Hi!
Thanks a lot! I'd love to get ImHex onto the Fedora repo (including possibly building and shipping a official .rpm if we can get it setup)

About your request, there already are some options to do this which are being used for various other distro repos right now. They can be found here: https://github.com/WerWolv/ImHex/blob/master/lib/libimhex/CMakeLists.txt#L29-L81

This includes most of the bundled dependencies but not all of them. This is mainly due to them either not being available as packages or ImHex requiring custom versions or specific commits. So the ones that don't have an option like this should be built with ImHex directly

**Comment by jonathanspw** [comment] 2022-07-28 20:57
I did come across that file and those options to use some system libs.

There are plenty of exceptions for bundling libs in RPMs and your justification here might suffice.  Let me chat with some more knowledgeable on those policies.

**Comment by jonathanspw** [comment] 2022-07-30 00:26
Just an update on this I finally have it compiling properly in the Fedora/EPEL build environment.  I should have some test packages ready next week that perhaps some of your current FlatPak users could test out to verify that everything works as it should.

**Comment by jonathanspw** [comment] 2022-07-30 06:08
Anyone that would like to test a very early copy of the package (runs fine on my Fedora 36 machine):

https://koji.fedoraproject.org/koji/taskinfo?taskID=90249964

Direct RPM download: https://kojipkgs.fedoraproject.org/work/tasks/9964/90249964/ImHex-1.19.3-1.fc36.x86_64.rpm

**Comment by Daegalus** [comment] 2022-07-30 21:42
Can confirm I just installed it on Fedora 36 on my Surface Pro 7. 

The only thing, don't know if its a bug in ImHex or the packaging, the default Scaling in ImHex is Native, and its super tiny on my hidpi screen. My Gnome is set to 200%.

When I switched it from Native to 2.0x manually, it all looked fine. So not sure what "native" is supposed to do and if its working as intended.
![Screenshot from 2022-07-30 14-36-11](https://user-images.githubusercontent.com/670212/181997036-1163cd3f-3d5b-4a26-a009-e33f1c611577.png)

**Comment by WerWolv** [comment] 2022-07-30 21:47
@Daegalus Thanks for testing!
Some hidpi detection issues have been resolved yesterday, it's possible that this build comes from a commit that's older than the one fixing the issue.

Full Fedora support will be merged soon though so you can grab the latest rpm from the nightly artifacts then once they are getting built :)

**Comment by Daegalus** [comment] 2022-07-30 22:00
> @Daegalus Thanks for testing!
> Some hidpi detection issues have been resolved yesterday, it's possible that this build comes from a commit that's older than the one fixing the issue.
> 
> Full Fedora support will be merged soon though so you can grab the latest rpm from the nightly artifacts then once they are getting built :)

Sounds good, always happy to test. I might see about adding Flatpak support as a PR, since lots of users prefer that nowadays.

I've been looking for a great opensource hex editor and I saw this today and immediately installed on all my machines as it does everything I've always needed.

**Comment by WerWolv** [comment] 2022-07-30 22:02
@Daegalus Thank you :)
We already do have a flatpack! It can be found here: https://github.com/flathub/net.werwolv.ImHex
The store sadly doesn't have the latest version right now because ImHex needs GCC 12.1.0 to build it and their build server doesn't ship that yet. Should be comming somewhen in August though

**Comment by jonathanspw** [comment] 2022-07-30 22:59
@Daegalus check out the latest build at https://github.com/WerWolv/ImHex/actions/runs/2767434620#artifacts to get those commits mentioned above to see if it resolves your issue.

I hope to have ImHex in Fedora repositories in the next 2 weeks or so which I'm sure will be convenient for ya :)

**Comment by Daegalus** [comment] 2022-07-30 23:37
> @Daegalus check out the latest build at https://github.com/WerWolv/ImHex/actions/runs/2767434620#artifacts to get those commits mentioned above to see if it resolves your issue.
> 
> I hope to have ImHex in Fedora repositories in the next 2 weeks or so which I'm sure will be convenient for ya :)

I can confirm that this version works and the Native setting works correctly also. Thank you!

**Closed** 2022-07-30 23:41 UTC
