### ISSUE TITLE
[Bug] Wrong layout

### ISSUE THREAD

**Issue by matteobaccan** [WerWolv/ImHex#361] opened 2021-12-05 07:58 UTC
### Operating System

Windows

### What's the issue you encountered?

Hi

I have a display problem with windows 10.
There is a toolbar on top of the menu (red arrow) that shifts all the GUI of about 30px.
For this reason, I must to click about 30 pixels on top of the clickable area.
In this picture is possible to see the bar and the point where I must to click for open (for example) the menu: I have put a red circle where I must click.

![immagine](https://user-images.githubusercontent.com/200925/144738348-0134c883-c0ab-4edd-b6e4-26e77f5cbf8d.png)

### How can the issue be reproduced?

I only execute ImHex portable version

### ImHex Version

1.11.2

### 

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment] 2021-12-05 10:24
Duplicate of #302. Download and use the opengl32.dll linked in the release

**Closed by WerWolv** 2021-12-05 10:24 UTC
