### ISSUE TITLE
[Bug] Diffing cannot compare files with matching filename

### ISSUE THREAD

**Issue by desowin** [WerWolv/ImHex#1045] opened 2023-04-23 18:05 UTC
### Operating System

Linux

### What's the issue you encountered?

When two files with same filename are opened, the diffing window allows only to compare the file against itself and not one against the other.

### How can the issue be reproduced?

1. Create files to analyze, e.g. `build/ov3.bit` and `build.old/ov3.bit`
2. Open both `ov3.bit` files in ImHex 1.28.0
3. Open diffing window and try to compare the two opened files
4. Observe that diffing only allows to compare the file against itself and does not allow actual diffing of the two files.

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

AUR package

### Additional context?

The workaround is to rename the other file to have distinctive filename.

**Comment by WerWolv** [comment] 2023-04-23 18:39
Thanks for the report! This is a duplicate of #1034 and has been fixed about a week ago. You can try download the latest nightly version from https://imhex.werwolv.net, that should resolve the issue

**Closed by WerWolv** 2023-04-23 18:39 UTC
Labels: bug
