### ISSUE TITLE
[Bug] Bookmarks wont be saved

### ISSUE THREAD

**Issue by XD1674** [WerWolv/ImHex#1175] opened 2023-07-01 09:38 UTC
### Operating System

Windows

### What's the issue you encountered?

I was analyzing a file and created bookmarks so i know whats where. I wasnt editing the file or doing anything else, just adding bookmarks. Then i saved the file and the project to be sure all of it was saved. Then when i opened the project, i saw that all of the bookmarks were gone (it took 3 hours to label every part).

### How can the issue be reproduced?

1. open a file
2. add bookmarks, nothing else
3. save file and project
4. open project
5. all of bookmarks gone

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

release page on github using the installer windows_x86-x64.msi

**Comment by WerWolv** [comment] 2023-07-01 09:50
Hi
I can't reproduce the error myself locally. Are you sure you saved a project and not just hit File -> Save or File -> Save As?
If yes, would it be possible for you to send me your project file (Either here, per Discord or per E-Mail)? Unless ImHex messed up while saving the project, I might be able to recover the bookmarks from it

**Comment by WerWolv** [comment] 2023-07-01 10:29
Fixed in latest commit

**Closed by WerWolv** 2023-07-01 10:29 UTC
Labels: bug
