### ISSUE TITLE
[Bug] ImHex crashed during initial setup 1.36.2

### ISSUE THREAD

**Issue by Helltar** [WerWolv/ImHex#2038] opened 2024-12-28 20:18 UTC
### Operating System

Linux

### What's the issue you encountered?

ImHex crashed during initial setup!
Error: Received signal 'SIGABRT' (6)

![Screenshot_20241228_221709](https://github.com/user-attachments/assets/e529d508-db5e-4c21-a97d-eab1e8b892f8)

### How can the issue be reproduced?

Just launch

### ImHex Version

1.36.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

AppImage

### Additional context?

Arch Linux, KDE (Wayland). Clean AppImage startup (no old configuration files)

- [20241228_220922.log](https://github.com/user-attachments/files/18267531/20241228_220922.log)

**Comment by WerWolv** [comment] 2024-12-28 20:22
Hey!
That looks like a crash somewhere in GTK when setting up the splash window. Did previous releases of ImHex work for you or is this the first one you tried? To me it looks like an issue with your system in some way but it's hard to pin-point. I don't think this is specifically an ImHex issue

**Comment by Helltar** [comment] 2024-12-28 20:49
1.36.0 and 1.36.1 AppImage have the same issue for me

1.35.4 AppImage and earlier versions work fine

I tested the packaged version 1.36.2 (imhex-1.36.2-ArchLinux-x86_64.pkg.tar.zst), and everything is fine, it works

Hmm...

**Comment by WerWolv** [comment] 2024-12-28 20:59
Very interesting... Since that crash happens extremely early in the startup, there's not a lot of stuff that actually happens before this call. The only thing that was changed between 1.35.4 and 1.36.0 there are the following was removed:
https://github.com/WerWolv/ImHex/blob/811214ddb79b66dba5ca56021212f81f9d89d608/main/gui/source/window/linux_window.cpp#L96-L99

I can't see how that would cause an issue with GTK though. Would be interesting to know _what_ assert is failing exactly

**Comment by WerWolv** [comment] 2024-12-28 21:04
Do you get any stdout output if you launch ImHex through the terminal?

**Comment by Helltar** [comment] 2024-12-28 21:08
Here is the output from the terminal:

- [out.log](https://github.com/user-attachments/files/18267702/out.log)

**Comment by WerWolv** [comment] 2024-12-28 21:10
```
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

That's certainly interesting... Do other releases work for you? e.g if you install the `imhex` package from the AUR?

**Comment by Helltar** [comment] 2024-12-28 21:18
**imhex** and **imhex-bin** from AUR work fine, the issue is only with AppImage 1.36.0+

**Comment by WerWolv** [comment] 2024-12-28 21:24
Alright, it's definitely an AppImage issue. I found quite a few issues on other projects that talk about exactly the same thing. Apparently the issue is that AppImages don't setup `XDG_DATA_DIRS` correctly on some distros. 

Various other people were able to fix it by first setting that env var before launching the AppImages. Does that work for you too?

```
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
./imhex.AppImage
```

**Comment by Helltar** [comment] 2024-12-28 21:27
Yes, it works, thank you

**Comment by WerWolv** [comment] 2024-12-28 21:28
Awesome! I'll add a note about this to the readme then and close this issue. Thanks a lot for your help :)

**Closed by WerWolv** 2024-12-28 21:28 UTC
Labels: bug
