### ISSUE TITLE
[Bug] Attribute left_to_right/right_to_left not works in latest version

### ISSUE THREAD

**Issue by Asvel** [WerWolv/ImHex#777] opened 2022-10-10 20:23 UTC
### Operating System

Windows

### What's the issue you encountered?

Attribute left_to_right/right_to_left not works in latest version, 1.24.0 is OK but 1.24.1 and 1.24.2 are broken.

### How can the issue be reproduced?

![imhex-bitfield-bug](https://user-images.githubusercontent.com/2691565/194945902-6df2dd23-dc6d-43c1-b9a7-c18bffd176e4.png)

### ImHex Version

1.24.2

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by Asvel** [comment] 2022-10-10 20:47
Beside of the bug, if I set left_to_right, it changes the fields display order rather than data order, is this a designed behavior? I feel it's slightly counterintuitive, is there some approchs to always display in fields defined order?

For bytes, in a file it is byte01, byte02, byte03..., we define struct fields and it consumes and displays in data flow order.
For bits, in a byte it is bit7..bit0, we define bitfield fields and it can consume in data flow order by setting left_to_right, but it always displays in opposite order to the data flow.

**Comment by WerWolv** [comment] 2022-10-11 06:54
Hey thanks for the report!
I fixed the bug with the broken attributes yesterday in the pattern language and it should come to ImHex soon.
About the order, yes this is intended behaviour. The issue is that if automatic left alignment, we have no way of knowing where exactly the left most bit is. For example for a bitfield like this:
```rust
bitfield Test {
    a : 5;
    b : a;
};
```
The size of b directly depends on where a is placed in memory but we'd need to layout a and b first to know where a will be placed. That gives you a circular reference.

Instead you just need to use `padding` fields to make sure your fields end up at the location where you want them to be.

**Comment by WerWolv** [comment] 2022-10-11 07:33
Fixed in e32a85a33f04e618439353224cc54ab7a5b51281

**Closed by WerWolv** 2022-10-11 07:33 UTC
