### ISSUE TITLE
[Bug] Cursor is not properly mapped to the window

### ISSUE THREAD

**Issue by squareless** [WerWolv/ImHex#1762] opened 2024-06-14 22:41 UTC
### Operating System

Windows

### What's the issue you encountered?

The issue I encountered is that whatever function gets the position of the cursor, it does not take into account Titlebar size and border size overall (I'm assuming).
What ends up happening is that mouse cursor is always higher than it supposedly points to, making it akward or impossible to use in the long run.
![ImHexCursorIssue](https://github.com/WerWolv/ImHex/assets/20949197/25f8dc86-b2c2-46e9-8f10-f41123b3d156)

### How can the issue be reproduced?

Open latest Windows.msi release.
Open ImHex and try to point to anything in window client area.

### ImHex Version

1.34.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by asdf141** [comment] 2024-06-22 12:56
https://github.com/WerWolv/ImHex/assets/157879116/a8de0708-4dc6-4823-8ded-a639e832dc6f

Same issue here, 1.34.0
btw nice logo

**Comment by iTrooz** [comment] 2024-06-22 13:00
Hey, I'm going to close this as duplicate of https://github.com/WerWolv/ImHex/issues/1625

**Closed by iTrooz** 2024-06-22 13:00 UTC
Labels: bug
