### ISSUE TITLE
[Bug] Crash when trying to place a pattern

### ISSUE THREAD

**Issue by DimaLeon2000** [WerWolv/ImHex#1033] opened 2023-04-12 21:54 UTC
### Operating System

Windows

### What's the issue you encountered?

When I try to place a pattern when whether any file is currently open or not, the program will trigger a SIGSEGV and crash.

### How can the issue be reproduced?

Edit -> Place pattern... -> Built-In Type -> Single/Array -> any pattern type

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

### Additional context?

The log goes as follows:
> [06:44:58] [INFO]  [main] Welcome to ImHex 1.28.0!
> [06:44:58] [INFO]  [main] Native scaling set to: 1.0
> [06:44:58] [INFO]  [main] Task 'Setting up environment' finished in 0 ms
> [06:44:58] [INFO]  [main] Task 'Creating directories' finished in 3 ms
> [06:44:58] [INFO]  [main] Task 'Loading settings' finished in 0 ms
> [06:44:58] [INFO]  [main] Task 'Loading plugins' finished in 110 ms
> [06:44:58] [INFO]  [main] Task 'Checking for updates' finished in 0 ms
> [06:45:00] [INFO]  [main] Task 'Loading fonts' finished in 1753 ms
> [06:45:23] [FATAL] [main] Exception raised: 0xC0000005
> [06:45:23] [FATAL] [main] Terminating with signal 'SIGSEGV' (11)
> [06:45:23] [FATAL] [main]   hex::stacktrace::getStackTrace()
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   _C_specific_handler
> [06:45:23] [FATAL] [main]   _chkstk
> [06:45:23] [FATAL] [main]   RtlRaiseException
> [06:45:23] [FATAL] [main]   KiUserExceptionDispatcher
> [06:45:23] [FATAL] [main]   hex::plugin::builtin::ViewPatternEditor::drawPatternTooltip(pl::ptrn::Pattern*)
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   ??
> [06:45:23] [FATAL] [main]   BaseThreadInitThunk
> [06:45:23] [FATAL] [main]   RtlUserThreadStart

**Comment by WerWolv** [comment] 2023-04-12 21:57
Thanks for the report! This is a duplicate of #1013 and has been fixed a few days ago. You can download the latest nightly release from https://imhex.werwolv.net to have it fixed or wait until a new full version is released

**Closed by WerWolv** 2023-04-12 21:57 UTC
Labels: bug
