### ISSUE TITLE
[Bug] ImGui randomly crashes when applying synced pattern

### ISSUE THREAD

**Issue by Nintynuts** [WerWolv/ImHex#1074] opened 2023-05-15 22:43 UTC
### Operating System

Windows

### What's the issue you encountered?

While pattern sync is enabled, sometimes editing a pattern will cause a crash. Doing the same edit after recovering the session doesn't cause the same crash.

### How can the issue be reproduced?

For me it doesn't happen every time I edit, but usually after a few. It may happen more frequently with more files open.
To test it was not related to my pattern or file, I created a binary file and pattern for it (below) and since I found that I could open the same file multiple times, I opened it lots of times. With auto evaluate enabled, I just modified names of variables and it crashed.

test pattern:
```
bitfield Test{
    a0:1;
    a1:1;
    a2:1;
    a3:1;
    a4:1;
    a5:1;
    a6:1;
    a7:1;
};

Test test[35] @ 0x0;
```

test hex:
```
01 02 04 08 10 20 40 80 03 05 09 11 21 41 81 06 0A 12 22 42 82 0C 14 24 84 18 28 48 88 30 50 90 60 A0 C0
```

### ImHex Version

1.28.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

MSI

**Comment by iTrooz** [comment] 2023-07-30 09:39
We recently fixed an issue (race condition IIRC ?) that made ImHex crash when editing the pattern with "auto evaluate" enabled. Could you check if you can still reproduce the issue on the latest release (and the latest nightly) ?

**Comment by Nintynuts** [comment] 2023-07-31 18:38
I installed 1.30.1 yesterday to try and fix an issue with pattern formatting (which only partially worked) and at one point when I have the sync enabled it did crash like it has before. was that the build you're referring to, or a newer one?

**Comment by iTrooz** [comment] 2023-08-01 10:07
IIRC we haven't issued a new release since the bug was fixed, so could you try with the latest nightly ? (At the bottom of https://imhex.werwolv.net/)

**Comment by iTrooz** [comment] 2023-11-13 11:23
AFAIK that issued has been resolved, closing

**Closed by iTrooz** 2023-11-13 11:23 UTC
Labels: bug
