### ISSUE TITLE
Text cursor not moving to the correct location with ctrl+c -> ctrl+v

### ISSUE THREAD

**Issue by german77** [WerWolv/ImHex#1950] opened 2024-11-04 16:56 UTC
### Operating System

Windows

### What's the issue you encountered?

Wrong cursor position that cause multiple issues. Seems to happen in just some lines and not the whole document.
![bug](https://github.com/user-attachments/assets/f9961933-9349-4bfa-9848-ea641d83e5d6)
![bug2](https://github.com/user-attachments/assets/8d97a860-1bb4-4486-ab6c-103495813c70)

### How can the issue be reproduced?

Selecting a line of code then copy paste multiple times. Results in the cursor positioning in the wrong location. Using ctrl+z to revert the changes will keep some of the text on the editor.

Additionally double click on a word will select the previous text block instead of the word you where hovering.

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

### Additional context?

Reproduced in two computers with windows 10. Pattern script: https://github.com/german77/TheDudeToHuman/blob/master/imhex.pattern

**Comment by paxcut** [comment] 2024-11-04 18:18
The problem you are having is that you must have copy pasted the code from some editor that uses `\t` for tabs. ImHex uses spaces for tabs and there is a PR that changes the tabs to spaces automatically for you that is waiting to be merged. In the mean time you can get around this problem by removing all the tabs (you can find them because the cursor jumps 4 spaces in one click) and using spaces instead.

**Comment by german77** [comment] 2024-11-04 18:22
Just noticed it was the tab causing the issues. Do you mind linking the PR. I don't see it on the list.

**Comment by paxcut** [comment] 2024-11-04 22:23
There isn't a PR specifically for converting tabs to spaces. The way I commit changes and create PRs has changed recently. I used to submit many changes into single PRs but now I create separate ones for each separate change set defined by an issue, a feature, improvement, etc... The (incorrect) code that changes Tabs to spaces can be found in PR #1700 but that is an old type of PR so it is set to draft. All the non-draft PRs should (eventually) add up to the draft PRs.

 When I  wrote the reply to your issue I was certain that the code was added to one of the smaller PRs but now I am not sure and I'm not going to search for it because that's a pita. I know I said that the code that changes tabs to spaces is waiting to be merged, but if it isn't already it will soon be and the code will hopefully also be correct. 

Tabs are really evil and using tabs in the text editor causes many problems besides the ones you found. Search replace, syntax coloring, error markings and many more are affected by them because tabs break the line, column coordinate system we use to locate text in the editor. Initially tabs were incorporated to the line,column coordinates but that makes the code a lot more complex than it needs to be if we simply avoid them altogether. 

As such, code created within the editor will always be tab free so the only way to introduce tabs is by pasting them into the code. You should avoid doing that and IMHO we should use spaces in all the editors that allow them, but it is understandably difficult to avoid the occasional tab to slip by being invisible as they are, so rest assured that this is an important part of the text editor which will not be overlooked or neglected. In fact, it deserves a PR of its own even if the code exists in another PR already. If you are interested look forward to it!

**Comment by german77** [comment] 2024-11-04 23:01
Thanks for the explanation. I like spaces as well because they are consistent between editors. This case is just as you described. I copied code from another program which happens to use tabs so it wasn't really apparent in imhex until I used notepad++ and saw the tabs.

**Comment by paxcut** [comment] 2024-11-05 09:29
I finished with the fixes for this issues. I extended and implemented correctly the changes hinted in the draft PR. Fix changes exist in two PRs [one](https://github.com/WerWolv/libwolv/pull/27) to the libwolv repository and the other to PR #1951. I tested the pattern you posted and while it shows both errors without the fixes, they are no longer reproducible when fixes are applied.

**Closed** 2024-11-24 10:31 UTC
Labels: bug
