### ISSUE TITLE
[Feature] Use Wayland native

### ISSUE THREAD

**Issue by 6543** [WerWolv/ImHex#1941] opened 2024-10-23 14:00 UTC
### What feature would you like to see?

it would be nice to have it run native via wayland, so e.g. fractial scaling works

### How will this feature be useful to you and others?

redable text:

![image](https://github.com/user-attachments/assets/af59c584-bff6-4ff0-88e8-e3fb6a1b3ef4)

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment] 2024-10-23 14:22
Duplicate of https://github.com/WerWolv/ImHex/issues/30

**Closed by WerWolv** 2024-10-23 14:22 UTC
Labels: feature request

**Comment by 6543** [comment] 2024-10-23 14:58
@WerWolv sadly it's not an duplicate ... as this asks for native wayland support not just support.

It's fine to mark it as wontfix if you plan to relay on xwayland in the long run ...

**Comment by 6543** [comment] 2024-10-23 15:04
I use the flatpak version ... as the nix packaged did not want to start, in this case it looks like an packaging issue rather than an upstream - thanks for clarification :)

**Comment by Twig6943** [comment] 2024-10-29 20:41
> We don't rely on xwayland though. It depends on what version of glfw you have installed. If you install the x11 version on wayland it will use xwayland but if you're using the wayland version it will run natively

Soo.. which packages support wayland?

**Comment by WerWolv** [comment] 2024-10-30 09:04
@Twig6943 Every package that uses glfw 3.4 or later supports both X11 and Wayland at the same time. I believe right now that's the rpm packages, the Arch Linux package and the latest Ubuntu one.

Alternatively, if you build ImHex yourself, you can make it use Wayland by making sure to install the glfw-wayland package

**Comment by Twig6943** [comment] 2024-10-30 21:43
Could u test out the appimage & flatpak pkgs and get back to me?

**Comment by 6543** [comment] 2024-10-30 23:49
the flatpak for flathub uses xorg socket -> xwayland

![image](https://github.com/user-attachments/assets/32623245-50ce-416f-a0c7-81534e82477f)

**Comment by Twig6943** [comment] 2024-10-31 04:59
What about the appimage?

**Comment by 6543** [comment] 2024-10-31 15:53
official appimage form latest release also uses xwayland -> tested with xeyes trick

**Comment by Twig6943** [comment] 2024-10-31 18:21
soo both distro agnostic pkgs use xwayland :+1: (ngl sad too see :disappointed: )

**Comment by WerWolv** [comment] 2024-10-31 18:25
Again, you can build it yourself from source and it will use Wayland. Once Ubuntu finally updates glfw, both the Flatpak and the AppImage will also start working with both X11 and Wayland natively right away.

**Comment by Twig6943** [comment] 2024-10-31 18:35
> Again, you can build it yourself from source and it will use Wayland. Once Ubuntu finally updates glfw, both the Flatpak and the AppImage will also start working with both X11 and Wayland natively right away.

Any ETA on that?

**Comment by WerWolv** [comment] 2024-10-31 21:18
> > Again, you can build it yourself from source and it will use Wayland. Once Ubuntu finally updates glfw, both the Flatpak and the AppImage will also start working with both X11 and Wayland natively right away.
> 
> Any ETA on that?

Ask Canonical, not me lol

**Comment by Twig6943** [comment] 2024-11-23 22:06
@WerWolv could u rename & reopen this issue? Rename it to something like "Wayland backend on distro agnostic pkg"

**Comment by 6543** [comment] 2024-11-23 23:42
Done for you #1967
