### ISSUE TITLE
[Bug] Patterns not loading for filetypes

### ISSUE THREAD

**Issue by ghost** [WerWolv/ImHex#1189] opened 2023-07-13 02:43 UTC
### Operating System

Linux

### What's the issue you encountered?

Compiled ImHex from AUR Arch for arm64 aarch platform.
The _/root/.local/share/imhex/patterns_ contains hexpat files, but no filetypes are being recognized by ImHex automatically. Pattern data shows empty window.

**Terminal output:**
[22:34:00] [INFO]  [main] Welcome to ImHex 1.30.1!
[22:34:00] [INFO]  [main] Compiled using commit makepkg@cc55ca3
[22:34:00] [INFO]  [main] Native scaling set to: 1.1
[22:34:01] [INFO]  [main] Task 'Setting up environment' finished in 5 ms
[22:34:01] [INFO]  [main] Task 'Creating directories' finished in 54 ms
[22:34:01] [INFO]  [main] Task 'Migrate config to .config' finished in 1 ms
[22:34:01] [INFO]  [main] Task 'Loading settings' finished in 3 ms
[22:34:01] [INFO]  [main] Task 'Loading plugins' finished in 240 ms
[22:34:02] [INFO]  [main] Task 'Checking for updates' finished in 1332 ms
[22:34:03] [INFO]  [main] Task 'Loading fonts' finished in 2038 ms
[22:34:03] [INFO]  [main] Running on Linux 4.19.157-perf+ #1 SMP PREEMPT Mon Mar 20 20:16:33 IST 2023 (aarch64)
[22:34:03] [INFO]  [main] Using 'Mesa' GPU

### How can the issue be reproduced?

Open ImHex
Open Extras -> Content Store
Download COFF, PE, ZIP patterns
Close ImHex
Reopen ImHex
Load EXE or ZIP
View pattern data
Pattern data window empty

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

yay (AUR)

### Additional context?

Android proot environment via Termux

**Comment by paxcut** [comment] 2023-07-13 03:17
I may not be able to help here because this seems to be an error that doesn't occur in windows, but I there is some details that are not fully described.  I understand that you build ImHex to run on ARM64 for Android linux and that may present some technical difficulties but I m not sure I understand what the nature of the issue you are experiencing is.

Normally, when certain file types are detected by ImHex loading them triggers a dialog to load a pattern for it and run it on the file. If for some reason that doesn't work, one can still load the pattern manually through the import menu and run it manually using the green play button.

Is this error about the automatic detection not occurring? The way I understand it, you need to load the magic files from Content Store to be able to detect the file types. If that fails,  are you able to import the patterns manually? The pattern should be displayed in the pattern editor window after it is imported. To run it on the loaded file click the green play button to create output that will show on the pattern data window.

If you are not able to import patterns manually do you see any error message when you try? If they load but cannot be run, are there error messages produced in the console window?

**Comment by awristen28** [comment] 2023-07-13 03:44
Yes it is about automatic detection of patterns. That dialog doesn't show, however this does work on the windows version. The patterns can be imported from file without error.

**Comment by paxcut** [comment] 2023-07-13 04:14
Your description says that no file types are recognized but in the reproduction steps you mention .exe and .zip only. Those two may not work because of the mime types may not be registered under linux. Does the elf or tar pattern load automatically? I have confirmed the work on windows although the test file for elf has a weird .elf extension.

**Comment by WerWolv** [comment] 2023-07-13 05:09
Make sure you have the "Standard Magic" magic database from the content store installed. That's the thing that allows ImHex to determine the type of file you loaded.
You can verify that it's working after installing it by opening the Data Information view, clicking on "Analyze Page" and then checking if a MIME type and file description is being displayed there.

**Comment by awristen28** [comment] 2023-07-13 06:36
After looking a my /root/ home directory, I saw a bunch of .mgc files in that path that got dumped there. Moved them into /root/.local/share/imhex/magic and the auto-detect feature started working again.

**Comment by iTrooz** [comment] 2023-07-13 06:53
If you launch Imhex again, do these .mgc files in /root get created again ?

**Comment by awristen28** [comment] 2023-07-13 07:46
Did a fresh install and deleted .config/imhex and .local/share/imhex. Upon install, both pattern and magic directories are empty. The content store seems to think they are installed.
[https://imgur.com/a/2TcPRCd](url)
When clicking remove and then download, the hexpat files show up in .local/share/imhex/patterns
This is the same for magic. Upon downloading the standard magic, all of the .mgc files get dumped in /root home directory and have to be moved into .local/share/imhex/magic

**This is the first run log:**
[03:12:05] [INFO]  [main] Welcome to ImHex 1.30.1!
[03:12:06] [INFO]  [main] Compiled using commit makepkg@cc55ca3
[03:12:06] [INFO]  [main] Native scaling set to: 1.1
[03:12:06] [INFO]  [main] Task 'Setting up environment' finished in 0 ms
[03:12:06] [INFO]  [main] Task 'Creating directories' finished in 34 ms
[03:12:06] [INFO]  [main] Found config file in /usr/bin/imhextermux/files/usr/libexec/proot/config! Migrating to /root/.config/imhex/config
[03:12:06] [INFO]  [main] Task 'Migrate config to .config' finished in 2 ms
[03:12:06] [ERROR] [main] Failed to load configuration! [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: ''
[03:12:06] [INFO]  [main] Task 'Loading settings' finished in 3 ms
[03:12:06] [INFO]  [main] Task 'Loading plugins' finished in 116 ms
[03:12:06] [INFO]  [main] Task 'Checking for updates' finished in 0 ms
[03:12:09] [INFO]  [main] Task 'Loading fonts' finished in 2344 ms
[03:12:09] [INFO]  [main] Running on Linux 4.19.157-perf+ #1 SMP PREEMPT Mon Mar 20 20:16:33 IST 2023 (aarch64)
[03:12:09] [INFO]  [main] Using 'Mesa' GPU

After downloading all of the patterns, libs etc.and reloading a file I get this:
[03:39:59] [FATAL] [main] Terminating with signal 'SIGSEGV' (11)
[03:39:59] [FATAL] [main] Received signal 'SIGSEGV' (11)
Segmentation fault
[root@localhost ~]# imhex
bash: /bin/imhex: No such file or directory
[root@localhost ~]# /usr/bin/imhex
bash: /usr/bin/imhex: No such file or directory
[root@localhost ~]#   
Like it wiped itself off the disk. Reinstall.

Went tor run imhex again and now it loads the patterns.

**Comment by ershov** [comment] 2023-08-01 09:43
Same here.
No patterns are loading automatically. And I haven't found any way to load anything manually - only by copy and paste of the source text.

OS: MacOS (latest)

**Comment by iTrooz** [comment] 2023-08-01 10:01
Hey, could you try using the latest nightly ? (At the bottom of https://imhex.werwolv.net/)
In this version, if you go in File -> Import -> Pattern file, do you see patterns ?

Also, please avoid using the word "latest". Most of the time, we have no idea what "latest" is, so you really need to check your version

**Comment by ershov** [comment] 2023-08-01 13:36
Hey thanks for your response.

The MacOS version is: 13.4.1 (22F82)

The "File -> Import -> Pattern file" works but it's a very unobvious way of doing it. I'd expect it to be available somewhere around the pattern editor. And it'd be great if the load dialog had a search bar and if the things were sorted.

I tried the nightly build - automatic load still doesn't work. Manual works with older versions too.

**Comment by iTrooz** [comment] 2023-08-01 22:56
That's weird, it works for me (commit `30b202cf0ca56211fb47f82be548513e6cbc3bac`, latest nightly as of right now)

Could you verify:
1) That you have downloaded "Standard magic", under "Magic files" in the content store ?
2) That you have .mgc files in the `magic` directory of ImHex ? (No idea where it is on MacOS, check Help -> About -> ImHex directories
3) That you have a .mgc file for the particular mime type of the file that you are opening

What's the mime type of the file you are opening btw ?

**Comment by ershov** [comment] 2023-08-02 11:19
Ok I got it.

The bug is that *.mgc files are in `/Applications/imhex.app/Contents/Resources` but they must be in `/Applications/imhex.app/Contents/MacOS/magic`. As soon as I moved them, it started to work.

This is specific to MacOS.

**Comment by iTrooz** [comment] 2023-08-02 11:42
Pretty sure you got the same bug

**Using the latest nightly**, could you:
-  remove "Standard magic"
- verify there are no *.mgc files in `magic`
- download "Standard magic"
- verify there are *.mgc files in `magic`, and no *.mgc files in `Resources` ?

**Comment by ershov** [comment] 2023-08-02 20:58
Now it worked. Not sure what went wrong last time, possibly two instances of the application collided.

Now that I removed all installations and put just one into the /Applications folder, it worked. Also checked it to work in another directory.

A few observations:
1. The initial installation lacks the "Standard Magic" at all. It only has `portable_executable_magic` and `nintendo_switch_magic`, not the most useful ones (note absence of `.mgc` extension).
2. After the Standard Magic is downloaded, it works immediately. The files are downloaded into the user directory (not /Application) which is ok.
3. The user path has an extra "imhex" in it. E.g. `~/Library/Application Support/imhex/imhex/patterns` (note double `imhex`).
4. When I click "Remove" on "Standard Magic", it indicates as removed but still stays on the filesystem and keeps working.

Things I would suggest to do, if I may:
1. Add "Standard Magic" into the installation bundle so that it works out-of-the-box.
2. Remove the extra `imhex` from the user data path (the existing installations should continue to work if you put it in the config). You might explicitly add these paths to the "Paths" setting or keep it hidden.
3. When importing the pattern, sort the list of patterns AND add a search box.
4. Add buttons to load/save patterns somewhere around the pattern editor.
5. Add "Download All" and "Update All" buttons to Online Store and/or checkbox selection of items with "select/deselect all".

For consistency, the "Remove" button should work too but I hardly can imagine anyone using it.

**Comment by paxcut** [comment] 2023-08-02 22:30
observations:
1. Standard magic is made available in the content store and it can be obtained from there.
3. When you say "the user path" do you mean in the folders list of the about menu? I cand find user path anywhere else. I checked the entries in the about folders tab and all entries have only one imhex in their name.

Suggestions:
1. See observation 1 reply above.
2.  ditto observation 3. Adding paths to the Path is for the user to add additional folders to the various file finders.
3. When importing a pattern use the browse button that gives you a file finder and the ability to sort and search.
4. Patterns are not loaded or saved, they are imported and exported. The pattern editor is separate for each provider so it makes no sense to add buttons there. To save pattern go to menu File>Export>Pattern file.
5. There is already a "Download All" button in content store for patterns. It is shaped like a cloud. "Update All" and "Download All" do the same thing. Adding a "Remove All" seems like a bad idea. Check-boxes for each entry in content store would be confusing because each entry already has a button with the appropriate action as a label. Selecting all boxes is the same as download all button.
6. This issue is for pattern files not loading automatically bug. Please open a discussion or a separate issue to make suggestions so that interested parties can locate them easily.

**Comment by iTrooz** [comment] 2023-08-02 22:50
I'm going to close the issue since this is resolved

**Closed by iTrooz** 2023-08-02 22:50 UTC
Labels: bug

**Comment by ershov** [comment] 2023-08-03 08:25
> 5\. It is shaped like a cloud

Ah that's what it is. There is a cloud button but it's grayed out (inactive) and doesn't work.

Is there any particular reason why you don't ship a standard functionality with the app (while including "nintendo_switch_magic")?

Double `imhex` on MacOS:
![image](https://github.com/WerWolv/ImHex/assets/449936/aa09702c-c9b1-4fe5-b439-f74b9117cc98)

> When importing a pattern use the browse button that gives you a file finder and the ability to sort and search

Luckily, sorting is already fixed in the Nightly.. thank you.

**Comment by paxcut** [comment] 2023-08-03 08:48
yes, cloud icon will be grayed out if nothing is available to download. It should work if some pattern needs updating.
Probably so you always have the latest, but I don't really know.
Does the path with two imhex exist? It could be a problem with your os. 
Please don't post to this issue unless you are going to discuss something related to it. If you have questions or want to make comments open a new discussion. If you have problems or doubts open a new issue.
Your welcome.
