### ISSUE TITLE
[Bug] Graphical corruption and mouse clicking incorrect on Windows 10

### ISSUE THREAD

**Issue by Poikilos** [WerWolv/ImHex#1839] opened 2024-08-05 15:19 UTC
### Operating System

Windows

### What's the issue you encountered?

- Several parts of the interface are black boxes
- hovering over links underlines the wrong link
- You have to hover inside of one of the black boxes above the smiley face ("leave feedback" button) to highlight or click it. Same goes for:
  - first run buttons (including "data that will be shared" expansion box)
  - toolbar (top buttons)
  - menubar (top menus)
  - dialog box buttons
  - tabs
- There is no icon in the start menu for the shim (C:\ProgramData\chocolatey\bin\imhex-gui.exe). v1.33.2 had an icon I think, but it was just called "shim", "chocolatey-shim" or something similar as the caption.
- It opens a mandatory Command Prompt behind the Window

### How can the issue be reproduced?

On Windows 10, install via:
- PowerShell (Administrator)
- `choco install imhex` (or `choco upgrade imhex` if already installed)

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

chocolatey

### Additional context?

![image](https://github.com/user-attachments/assets/1b1acef9-e96a-478c-9e67-2e1e954204fa)

**Comment by WerWolv** [comment] 2024-08-05 15:35
Hey!
Could you maybe upload a screenshot? The black squares / mouse offset is most likely caused by Intel's terrible graphics drivers (See #1625 and the readme). The icon issue probably comes from the Chocolatey package not being configured correctly, please report it to the person that maintains the package there, it's not official.

**Comment by WerWolv** [comment] 2024-08-05 16:42
Closing as duplicate yeah, this is a Intel Driver bug.

**Closed by WerWolv** 2024-08-05 16:42 UTC
Labels: bug
