### ISSUE TITLE
[Bug] AppImage 1.28 crashes when trying to place a pattern

### ISSUE THREAD

**Issue by gbl** [WerWolv/ImHex#1046] opened 2023-04-26 10:48 UTC
### Operating System

Windows

### What's the issue you encountered?

The appimage 1.28 crashes when you try to place a pattern. As I'm using Ubuntu 20.04, I didn't try to install the .deb version as it seems to need Ubuntu 22.04.

### How can the issue be reproduced?

Start the AppImage with any file - I tried with several different files, the file doesn't seem to matter.

```
$ /tmp/imhex-1.28.0-x86_64.AppImage mea_20221110165145_12bit.mea 
[12:41:38] [INFO]  [main] Welcome to ImHex 1.28.0!
[12:41:38] [INFO]  [main] Native scaling set to: 1.0
[12:41:38] [INFO]  [main] Task 'Setting up environment' finished in 48 ms
[12:41:38] [INFO]  [main] Task 'Creating directories' finished in 19 ms
[12:41:38] [INFO]  [main] Task 'Migrate config to .config' finished in 0 ms
[12:41:38] [INFO]  [main] Task 'Loading settings' finished in 11 ms
[12:41:39] [INFO]  [main] Task 'Loading plugins' finished in 476 ms
[12:41:39] [INFO]  [main] Task 'Checking for updates' finished in 0 ms
[12:41:41] [INFO]  [main] Task 'Loading fonts' finished in 1840 ms
```

Left-click the byte at 00000000.
Right-click, select Place Pattern -> Built-in Type -> Single -> u8
The application crashes. leading to

```
[12:41:47] [FATAL] [main] Terminating with signal 'SIGSEGV' (11)
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/lib/x86_64-linux-gnu/libimhex.so.1.28.0(_ZN3hex10stacktrace13getStackTraceEv+0x50) [0x7f14b8489980]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/bin/imhex(+0x42b29) [0x55d52d340b29]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/bin/imhex(+0x43749) [0x55d52d341749]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/runtime/compat/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f14b7e95520]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/share/imhex/plugins/builtin.hexplug(+0x436ca5) [0x7f144a546ca5]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/bin/imhex(+0x4411f) [0x55d52d34211f]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/bin/imhex(+0x4411f) [0x55d52d34211f]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/bin/imhex(+0x46f47) [0x55d52d344f47]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/bin/imhex(+0x2856c) [0x55d52d32656c]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/runtime/compat/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f14b7e7cd90]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/runtime/compat/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f14b7e7ce40]
[12:41:47] [FATAL] [main]   /tmp/.mount_imhex-VKuaDn/usr/bin/imhex(+0x31645) [0x55d52d32f645]
Segmentation fault (core dumped)
```

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

I downloaded the AppImage from the releases page, did a `chmod +x`, and ran the image from the shell

### Additional context?

Ubuntu 20.04, using the AppImage. This seems to happen with any file I edit, it's not restricted to a specific file.

I did not install the .service so I can't use File/Open, but drag/drop and opening from command line works.

The probem does not happen with the 1.27.1 AppImage.

**Comment by WasserEsser** [comment] 2023-04-30 16:38
The same happens on Windows, 1.28 crashes, 1.27.1 does not.

**Comment by WerWolv** [comment] 2023-04-30 16:41
Thanks for the report! This is a duplicate of #1013. Please update to the latest nightly release, the fix will be in the next full release

**Closed by WerWolv** 2023-04-30 16:41 UTC
Labels: bug
